In [31]:
import influxdb_client
import pandas as pd

In [32]:
TOKEN = '80pzM9UJharBRVfSbBIfecydGJsX80ihx2IZsd7UmAZUhUumZTIiX9jUqQNytXPxeVuZlgLmHAY6JOyHnLZuJw=='
URL = 'http://localhost:8086'
ORG = 'VCT'
BUCKET = 'HOUSE_HOLD_ENERGY'

In [33]:
client = influxdb_client.InfluxDBClient(url=URL, token=TOKEN, org=ORG)

In [34]:
query_api = client.query_api()

In [35]:
query = f'''
from(bucket: "{BUCKET}")
  |> range(start: 2006-12-16T00:00:00Z, stop: 2008-12-16T00:00:00Z)
  |> filter(fn: (r) => r["_measurement"] == "house_energy")
  |> filter(fn: (r) => r["_field"] == "Global_active_power" or 
                      r["_field"] == "Global_reactive_power" or 
                      r["_field"] == "Voltage" or 
                      r["_field"] == "Global_intensity" or 
                      r["_field"] == "Sub_metering_1" or 
                      r["_field"] == "Sub_metering_2" or 
                      r["_field"] == "Sub_metering_3")
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
'''

In [36]:
data_6_to_8 = query_api.query_data_frame(query=query)

In [37]:
query = f'''
from(bucket: "{BUCKET}")
  |> range(start: 2008-12-17T00:00:00Z)
  |> filter(fn: (r) => r["_measurement"] == "house_energy")
  |> filter(fn: (r) => r["_field"] == "Global_active_power" or 
                      r["_field"] == "Global_reactive_power" or 
                      r["_field"] == "Voltage" or 
                      r["_field"] == "Global_intensity" or 
                      r["_field"] == "Sub_metering_1" or 
                      r["_field"] == "Sub_metering_2" or 
                      r["_field"] == "Sub_metering_3")
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
'''

In [42]:
data_8_to_10 = query_api.query_data_frame(query=query)

In [40]:
data_6_to_8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1051596 entries, 0 to 1051595
Data columns (total 13 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   result                 1051596 non-null  object
 1   table                  1051596 non-null  int64
 2   _start                 1051596 non-null  datetime64[ns, UTC]
 3   _stop                  1051596 non-null  datetime64[ns, UTC]
 4   _time                  1051596 non-null  datetime64[ns, UTC]
 5   _measurement           1051596 non-null  object
 6   Global_active_power    1051596 non-null  object
 7   Global_intensity       1051596 non-null  object
 8   Global_reactive_power  1051596 non-null  object
 9   Sub_metering_1         1051596 non-null  object
 10  Sub_metering_2         1051596 non-null  object
 11  Sub_metering_3         1047527 non-null  float64
 12  Voltage                1051596 non-null  object
dtypes: datetime64[ns, UTC](3), float64(1), int64(1), object(8)
memory usage: 104.3+ MB

In [ ]:
data_8_to_10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1022223 entries, 0 to 1022222
Data columns (total 13 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   result                 1022223 non-null  object
 1   table                  1022223 non-null  int64
 2   _start                 1022223 non-null  datetime64[ns, UTC]
 3   _stop                  1022223 non-null  datetime64[ns, UTC]
 4   _time                  1022223 non-null  datetime64[ns, UTC]
 5   _measurement           1022223 non-null  object
 6   Global_active_power    1022223 non-null  object
 7   Global_intensity       1022223 non-null  object
 8   Global_reactive_power  1022223 non-null  object
 9   Sub_metering_1         1022223 non-null  object
 10  Sub_metering_2         1022223 non-null  object
 11  Sub_metering_3         1000313 non-null  float64
 12  Voltage                1022223 non-null  object
dtypes: datetime64[ns, UTC](3), float64(1), int64(1), object(8)
memory usage: 101.4+ MB

In [51]:
data = pd.concat([data_6_to_8, data_8_to_10])

In [52]:
data

,result,table,_start,_stop,_time,_measurement,Global_active_power,Global_intensity,Global_reactive_power,Sub_metering_1,Sub_metering_2,Sub_metering_3,Voltage
0,_result,0,2006-12-16 00:00:00+00:00,2008-12-16 00:00:00+00:00,2006-12-16 17:24:00+00:00,house_energy,4.216,18.400,0.418,0.000,1.000,17.0,234.840
1,_result,0,2006-12-16 00:00:00+00:00,2008-12-16 00:00:00+00:00,2006-12-16 17:25:00+00:00,house_energy,5.360,23.000,0.436,0.000,1.000,16.0,233.630
2,_result,0,2006-12-16 00:00:00+00:00,2008-12-16 00:00:00+00:00,2006-12-16 17:26:00+00:00,house_energy,5.374,23.000,0.498,0.000,2.000,17.0,233.290
3,_result,0,2006-12-16 00:00:00+00:00,2008-12-16 00:00:00+00:00,2006-12-16 17:27:00+00:00,house_energy,5.388,23.000,0.502,0.000,1.000,17.0,233.740
4,_result,0,2006-12-16 00:00:00+00:00,2008-12-16 00:00:00+00:00,2006-12-16 17:28:00+00:00,house_energy,3.666,15.800,0.528,0.000,1.000,17.0,235.680
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022218,_result,0,2008-12-17 00:00:00+00:00,2024-11-13 23:36:22.851239+00:00,2010-11-26 20:58:00+00:00,house_energy,0.946,4.000,0.000,0.000,0.000,0.0,240.430
1022219,_result,0,2008-12-17 00:00:00+00:00,2024-11-13 23:36:22.851239+00:00,2010-11-26 20:59:00+00:00,house_energy,0.944,4.000,0.000,0.000,0.000,0.0,240.000
1022220,_result,0,2008-12-17 00:00:00+00:00,2024-11-13 23:36:22.851239+00:00,2010-11-26 21:00:00+00:00,house_energy,0.938,3.800,0.000,0.000,0.000,0.0,239.820
1022221,_result,0,2008-12-17 00:00:00+00:00,2024-11-13 23:36:22.851239+00:00,2010-11-26 21:01:00+00:00,house_energy,0.934,3.800,0.000,0.000,0.000,0.0,239.700
1022222,_result,0,2008-12-17 00:00:00+00:00,2024-11-13 23:36:22.851239+00:00,2010-11-26 21:02:00+00:00,house_energy,0.932,3.800,0.000,0.000,0.000,0.0,239.550

In [53]:
data.reset_index(inplace=True, drop=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2073819 entries, 0 to 2073818
Data columns (total 13 columns):
 #   Column                 Dtype
---  ------                 -----
 0   result                 object
 1   table                  int64
 2   _start                 datetime64[ns, UTC]
 3   _stop                  datetime64[ns, UTC]
 4   _time                  datetime64[ns, UTC]
 5   _measurement           object
 6   Global_active_power    object
 7   Global_intensity       object
 8   Global_reactive_power  object
 9   Sub_metering_1         object
 10  Sub_metering_2         object
 11  Sub_metering_3         float64
 12  Voltage                object
dtypes: datetime64[ns, UTC](3), float64(1), int64(1), object(8)
memory usage: 205.7+ MB

#### Limpando dataframe

##### Retirando dados desnecessários

In [54]:
data.drop(columns=['result', 'table', '_start', '_stop', '_measurement'], inplace=True)
data

,_time,Global_active_power,Global_intensity,Global_reactive_power,Sub_metering_1,Sub_metering_2,Sub_metering_3,Voltage
0,2006-12-16 17:24:00+00:00,4.216,18.400,0.418,0.000,1.000,17.0,234.840
1,2006-12-16 17:25:00+00:00,5.360,23.000,0.436,0.000,1.000,16.0,233.630
2,2006-12-16 17:26:00+00:00,5.374,23.000,0.498,0.000,2.000,17.0,233.290
3,2006-12-16 17:27:00+00:00,5.388,23.000,0.502,0.000,1.000,17.0,233.740
4,2006-12-16 17:28:00+00:00,3.666,15.800,0.528,0.000,1.000,17.0,235.680
...,...,...,...,...,...,...,...,...
2073814,2010-11-26 20:58:00+00:00,0.946,4.000,0.000,0.000,0.000,0.0,240.430
2073815,2010-11-26 20:59:00+00:00,0.944,4.000,0.000,0.000,0.000,0.0,240.000
2073816,2010-11-26 21:00:00+00:00,0.938,3.800,0.000,0.000,0.000,0.0,239.820
2073817,2010-11-26 21:01:00+00:00,0.934,3.800,0.000,0.000,0.000,0.0,239.700
2073818,2010-11-26 21:02:00+00:00,0.932,3.800,0.000,0.000,0.000,0.0,239.550